### PR TITLE
Support whitelisting DIDs for alpha access

### PR DESCRIPTION
**Pull request by aurelticot**

### CODE REVIEW

**Review by tahpot — CHANGES_REQUESTED** [review]
Can you please merge `develop` into this branch. You will then see I have modified the navigation (merged user and developer). There is also now a `login` page.

From what I can gather, this access restriction is only restricting access to the `ai` page. We need to restrict access to all rest API endpoints, except login, to non whitelisted DIDs.

This can be done by creating a middleware verification function in express and then adding that function to any `router.use()` or `router.get/post()` method.

See here: https://chatgpt.com/share/670467c2-275c-8001-8f8b-6af00574f25c

I have added notion credentials into bitwarden (search Private Data Bridge).

Bonus: I have added a `Admin` checkbox in Notion. It would be great if the `api/rest/v1/admin` endpoints can be limited to admins.

**Comment by aurelticot** [comment]
> From what I can gather, this access restriction is only restricting access to the ai page. We need to restrict access to all rest API endpoints, except login, to non whitelisted DIDs.

The access is checked in `Utils.getNetwork()` which is used by the CLI commands as well as all the endpoints getting the `key` from the request.
I'll check how the login endpoint works to make sure it's not covered.

> I have added a Admin checkbox in Notion. It would be great if the api/rest/v1/admin endpoints can be limited to admins.

Ok

**Comment by aurelticot** [comment]
@tahpot the `/admin` endpoints currently don't require the `key` to be passed in the request, so we can't check the access and `admin` property.

Do you want me to do that in this PR?

**Review by tahpot — CHANGES_REQUESTED** [review]
> @tahpot the `/admin` endpoints currently don't require the `key` to be passed in the request, so we can't check the access and `admin` property.
> 
> Do you want me to do that in this PR?

Sorry, I missed this. Yes, please do.

> The access is checked in Utils.getNetwork() which is used by the CLI commands as well as all the endpoints getting the key from the request.

Can you disable the checks for the CLI?

Separately, when I open the login page, it's on an infinite reload loop. Can you take a look at that? I recall having this issue and then fixing it, so maybe something got lost in a merge?

Other than that, looking good.

**Comment by tahpot** [comment]
@aurelticot 

See my latest commit. `status` and `memory` can be public, they will be used in the future to work out which node to allocate resources to.

**Pull request merged**
